### ISSUE TITLE
handling for external dependencies

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#12]
* Be aware of what external dependencies exist for a given area of functionality
* Missing external dependencies should result in disabled functions -- not crashes
* In many cases, package-level granularity is sufficient (most device-level support)
* In other cases, finer granularity is required (most filesystem support)

Basically, we need to be able to determine the following for each type of device and format:
* can we activate/deactivate?
* can we create/destroy/resize?

We may also need to add something like:
* can we use this device normally? ("Is it suitable for normal I/O?")

**Comment by mulkieran** [comment]
Posted somewhat dated proposal at: https://mulhern.fedorapeople.org/proposals/availability/resources2.pdf. In particular, caching is no longer handled within the tasks, because it makes for a good deal of confusion and is not used generally. The patches that were part of the original proposal are now, of course, obsoleted by current development.

**Comment by vpodzime** [comment]
I went through the referenced PDF document. The design seems to be pretty complex, but I didn't have time to think about it enough to be able to tell if it's overly complicated or just as complex as it has to be. I'll get back to this next week (so that I can think about it over the weekend).

**Comment by mulkieran** [comment]
The only issues left that I am aware of are handling dependencies among blivet/libblockdev/anaconda and #159 covers that.
