### ISSUE TITLE
Hard to reproduce failure in tests/devices_test/device_packages_test.py - DevicePackagesTestCase

### ISSUE THREAD

**Issue by atodorov** [rhinstaller/blivet#154]
With Python3 I sometimes get this error:
```
======================================================================
FAIL: testPackages (device_packages_test.DevicePackagesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/html/blivet/tests/devices_test/device_packages_test.py", line 26, in testPackages
    self.assertListEqual(packages, list(set(packages)))
AssertionError: Lists differ: ['cryptsetup', 'mdadm'] != ['mdadm', 'cryptsetup']

First differing element 0:
cryptsetup
mdadm

- ['cryptsetup', 'mdadm']
+ ['mdadm', 'cryptsetup']
```
I've managed to isolate the issue down to the conversion from list to set and then back to list.

Initially packages is ['cryptsetup', 'mdadm'], then set(packages) becomes {'mdadm', 'cryptsetup'} which later becomes the list ['mdadm', 'cryptsetup'] and the assert fails. Converting to set under Python3 sometimes reverses the order of the elements but not always. Any ideas how to reproduce reliably or why that happens ?

**Comment by psav** [comment]
Would it make sense to modify this so that it compared them as sets. Though lists are order specific, depending on what is creating them, could mean they end up in a different order. It looks, however, like the order isn't important and just the presence of the element is. In which case, perhaps a set comparison would be better than a list comparison?

**Comment by mfalesni** [comment]
I believe when you sort both of them, it will work. `set` will not guarantee the order.

**Comment by atodorov** [comment]
@psav - comparing as sets should be enough. The test is checking for duplicates.

**Comment by msvbhat** [comment]
If you have both list as set, you can do a set union and check if the length increases.

**Comment by psav** [comment]
@atodorov in point of fact, the conversion to a set probably, I'm no expert here, has no order implication, just like dicts, so when you then cast it to a list, there is no defined order in which to read from the set, therefore, they could turn up in any order. I believe if you had more than 2 items in the list, you would probably have hit this error much more often.

**Comment by psav** [comment]
@atodorov If the test is supposed to be checking for duplicates, then perhaps all you need is to ensure that the list doesn't have a count greater than 1 for each element. Or, take the length of the list, and then take the length of a set(list) and see if the lengths differ, that would tell you if there were duplicates. If you want to check for duplicates, making both lists, sets would be a bad idea, as it would lose all non-unique elements from both of them.

**Comment by rplevka** [comment]
my 0.02$:
the `Set` is a non-indexed collection.
While the Set is being constructed, the items are being __sorted__ first, that's why you can't simply compare a list with a set.

```python
>>> a = [9,8,7,6,5,4,3,2,1,0]
>>> set(a)
set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
note, that strings are comparable as well (which seems to be your case):
```python
>>> 'foo' > 'bar'
True
>>> 'foo' < 'bar'
False
>>> set(['foo', 'bar'])
set(['foo', 'bar'])
>>> set(['bar', 'foo'])
set(['foo', 'bar'])

```
tip: sort your array before comparing it with a set

**Comment by atodorov** [comment]
@rplevka  - this is a simple test script:
```
packages = ['cryptsetup', 'mdadm']
s = set(packages)
l = list(s)
print(packages, s, l)
```

On Python2 for me it always produces the same results. On Python3 in 30 to 50% of the times the output differs (the set order is reversed) (try running in a loop bout 100 times). I get the thing that sets don't guarantee the order but I'm interested to find out why the difference is so visible with Python3 compared to Python2.

**Comment by rplevka** [comment]
@atodorov : 
ah! then it must be caused by the following [fix](https://mail.python.org/pipermail/python-announce-list/2012-March/009394.html).

According the [documentation](https://docs.python.org/2/library/stdtypes.html#set-types-set-frozenset), 

> A set object is an unordered collection of distinct [hashable](https://docs.python.org/2/glossary.html#term-hashable) objects.

A `hashable object` contains a [\_\_hash__()](https://docs.python.org/2/reference/datamodel.html#object.__hash__) function which return a hash for the object.
And here's why the fix has been introduced and how it works:

> The security issue exploits Python's dict and set implementations. Carefully
crafted input can lead to extremely long computation times and denials of
service. [1] __Python dict and set types use hash tables to provide amortized
constant time operations__. Hash tables require a well-distributed hash function
to spread data evenly across the hash table. The security issue is that an
attacker could compute thousands of keys with colliding hashes; this causes
quadratic algorithmic complexity when the hash table is constructed. To
alleviate the problem, __the new releases add randomization to the hashing of
Python's string types (bytes/str in Python 3 and str/unicode in Python 2),
datetime.date, and datetime.datetime__. This prevents an attacker from computing
colliding keys of these types without access to the Python process.

so while inside a single python execution, the calculated hash for a specific object remains the same,
it differs with every new invocation of python:

Python3 example:
```bash
$ cat test_hash3.py 
#!/usr/bin/python3


print('cryptsetup'.__hash__())
print('mdadm'.__hash__())
./test_hash3.py 
4439300755787086073
1129852268306016398
$ ./test_hash3.py 
-4692070451349341738
6240299351383006358
```
same script interpreted by Python 2:
```bash
$ cat test_hash.py 
#!/usr/bin/python


print('cryptsetup'.__hash__())
print('mdadm'.__hash__())
$ ./test_hash.py 
775420229536058113
4970439450721789084
$ ./test_hash.py 
775420229536058113
4970439450721789084

```
example of printing the hash inside a single loop using python3:
```python
>>> for i in range(1,10):
...     print('mdadm'.__hash__())
...     print('cryptsetup'.__hash__())
... 
-5278052330039079800
5130521905409093552
-5278052330039079800
5130521905409093552
-5278052330039079800
5130521905409093552
...
-5278052330039079800
5130521905409093552
```

..hope it answered your question

**Comment by atodorov** [comment]
@rplevka - thanks a lot
